name: pedro-fiuza-blazor-wasm
uses: actions/upload-artifact@v4
static_sites:
- name: site
  github:
    repo: Swimburger/BlazorWasmDigitalOcean
    branch: main
    deploy_on_push: true
  dockerfile_path: Dockerfile.build 
  output_dir: /output/wwwroot
  index_document: index.html
  catchall_document: index.html